version: '3'
services:


  database:
    image: coopersoft/mariadb-min:v1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/home/data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: p0stgr@s
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: k@ycl0ck
      TZ: Asia/Shanghai


  #          nosse4  stable4  latest2
  mediaservice:
    image: coopersoft/archives-media-service:nosse2
    restart: always
    ports:
      - "6699:6699"
    volumes:
      - "/home/data/weedfs:/data"
    environment:
      TZ: Asia/Shanghai

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "/home/data/redis:/data"
    command: redis-server --requirepass p0stgr@s

  rmqnamesrv:
    image: rocketmqinc/rocketmq
    restart: always
    ports:
      - 9876:9876
    volumes:
      - /home/data/rocketmq/logs:/home/rocketmq/logs
      - /home/data/rocketmq/store:/home/recketmq/store
    command: sh mqnamesrv

  rmqborker:
    image: rocketmqinc/rocketmq
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - /home/data/rocketmq/logs:/home/rocketmq/logs
      - /home/data/rocketmq/store:/home/rocketmq/store
      - /home/data/rocketmq/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    links:
      - rmqnamesrv:rmqnamesrv
    depends_on:
      - rmqnamesrv


  # rocket 控制台 非必要
#  rmqconsole:
#    image: styletang/rocketmq-console-ng
#    ports:
#      - 8087:8080
#    depends_on:
#      - rmqnamesrv
#    links:
#      - rmqnamesrv:rmqnamesrv
#    environment:
#      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876
#      - Dcom.rocketmq.sendMessageWithVIPChannel=false


  consul:
    image: consul:latest
    restart: always
    command: agent -server -bootstrap -ui -node=node1 -client=0.0.0.0
    ports:
      - 8500:8500
    volumes:
      - /home/data/consul:/consul/data


  keycloak:
    image: jboss/keycloak:10.0.2
    restart: always
    ports:
      - 8901:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mariadb
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: k@ycl0ck
      DB_PORT: 3306
    links:
      - database:database
    depends_on:
      - database

  gatewaysvr:
    image: coopersoft/cloud-gatewaysvr:1.0.1
    restart: always
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    depends_on:
      - consul
    links:
      - consul:consul


  # ==================  archive app ===================================================

  corpservices:
    image: coopersoft/construct-attach-corp-service:1.0.1
    restart: always
    expose:
      - "19001"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19001"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - database:database
      - rmqnamesrv:rmqnamesrv
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - database
      - rmqnamesrv
      - keycloak
      - consul

  projectservices:
    image: coopersoft/construct-project-service:1.0.1
    restart: always
    expose:
      - "19002"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19002"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - database:database
      - rmqnamesrv:rmqnamesrv
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - database
      - rmqnamesrv
      - keycloak
      - consul

  cacheservices:
    image: coopersoft/construct-project-cache-service:1.0.1
    restart: always
    expose:
      - "19003"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19003"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - rmqnamesrv:rmqnamesrv
      - redis:redis
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - redis
      - rmqnamesrv
      - keycloak
      - consul

  trustgatewaysvr:
    image: coopersoft/trust-gatewaysvr:1.0.1
    restart: always
    ports:
      - "5556:5556"
    environment:
      PROFILE: "prod"
      SERVER_PORT: "5556"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    depends_on:
      - consul
      - rmqnamesrv
      - redis
    links:
      - consul:consul
      - rmqnamesrv:rmqnamesrv
      - redis:redis




  camunda:
    image: coopersoft/construct-camunda-service:1.0.1
    restart: always
    ports:
      - 18086:18086
    environment:
      PROFILE: "prod"
      SERVER_PORT: "18086"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - database:database
      - rmqnamesrv:rmqnamesrv
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - database
      - rmqnamesrv
      - keycloak
      - consul


#  camundaconsole:
#    image: coopersoft/camunda-console:latest
#    ports:
#      - 18902:18902
#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "18902"
#      CAMUNDA_PORT: 18086
#    depends_on:
#      - database
#      - camunda
#    links:
#      - database:database
#      - camunda:camunda

  fireconstructcheck:
    image: coopersoft/construct-fire-check-service:1.0.1
    restart: always
    expose:
      - "19004"
    environment:
      PROFILE: "prod"
      SERVER_PORT: "19004"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - database:database
      - rmqnamesrv:rmqnamesrv
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - database
      - rmqnamesrv
      - keycloak
      - consul



  cms:
    image: coopersoft/little-cms-endpoint:0.0.1
    restart: always
    ports:
      - 17001:17001
    environment:
      PROFILE: "prod"
      SERVER_PORT: "17001"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - database:database
      - consul:consul
    depends_on:
      - database
      - consul
  # ==================  client ===================================================


  webclient:
    image: coopersoft/construct-webclient:1.0.1
    restart: always
    ports:
      - "5200:5200"
    network_mode: "host"
    environment:
      API_URL: 'http://192.168.1.21:5555'
      FILE_URL: 'http://192.168.1.21:6699'
      AUTH_URL: 'http://192.168.1.21:8901/auth'

  webcollaborativeclient:
    image: coopersoft/construct-collaborative-webclient:1.0.1
    restart: always
    ports:
      - "5201:5201"
    network_mode: "host"
    environment:
      API_URL: 'http://192.168.1.21:5556'
      FILE_URL: 'http://192.168.1.21:6699'
      AUTH_URL: 'http://192.168.1.21:8901/auth'

  website:
    image: coopersoft/construct-website:nosse-0.0.2
    restart: always
    ports:
      - "80:6698"
    network_mode: "host"
    volumes:
      - /home/data/website/resources.properties:/usr/local/openresty/nginx/conf/resources.properties
